name: build

on: workflow_dispatch

env:
  PY_ALL: 3.9 3.10 3.11 3.12 3.13 3.13t 3.14 3.14t pypy3.9 pypy3.10 pypy3.11

jobs:
  wheels:
    name: wheel ${{ matrix.platform || matrix.os }}(${{ matrix.target }})${{ matrix.manylinux && format(' - {0}', matrix.manylinux) || '' }}
    continue-on-error: ${{ matrix.platform == 'windows' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - &linux_auto
            os: ubuntu
            platform: linux
            manylinux: auto
            target: x86_64
          - <<: *linux_auto
            target: x86_64
            interpreter: pypy3.9 pypy3.10 pypy3.11
          - <<: *linux_auto
            target: i686
            interpreter: 3.9 3.10 3.11 3.12 3.13 3.14
          - <<: *linux_auto
            target: aarch64
            # rust-cross/manylinux2014-cross:aarch64 has issues with `ring`
            #container: ghcr.io/rust-cross/manylinux_2_28-cross:aarch64
          - <<: *linux_auto
            target: armv7
            interpreter: 3.9 3.10 3.11 3.12 3.13 3.14
          - &linux_musl
            os: ubuntu
            platform: linux
            manylinux: musllinux_1_1
            target: x86_64
          - <<: *linux_musl
            target: aarch64
          - <<: *linux_musl
            target: armv7
            interpreter: 3.9 3.10 3.11 3.12 3.13 3.14
          - &macos_base
            os: macos
            platform: macos
            target: x86_64
          - <<: *macos_base
            interpreter: pypy3.9 pypy3.10 pypy3.11
          - <<: *macos_base
            target: aarch64
          - <<: *macos_base
            target: aarch64
            interpreter: pypy3.9 pypy3.10 pypy3.11
          - &windows_base
            os: windows
            platform: windows
            target: x86_64
            interpreter: 3.9 3.10 3.11 3.12
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pyo3/maturin-action@v1
        with:
          rust-toolchain: stable
          command: build
          args: --release --out dist --interpreter ${{ matrix.interpreter || env.PY_ALL }}
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.platform == 'linux' && (matrix.manylinux || 'auto') || '' }}
          container: ${{ matrix.platform == 'linux' && matrix.container || '' }}
          docker-options: ${{ matrix.platform == 'linux' && '-e CI' || '' }}
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.platform || matrix.os }}-${{ matrix.target }}${{ matrix.manylinux && format('-{0}', matrix.manylinux) || '' }}
          path: dist

  wheels-pgo:
    name: pgo-wheel ${{ matrix.platform || matrix.os }} (${{ matrix.interpreter }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        manylinux: [auto]
        interpreter: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t"]
        include:
          - os: ubuntu-latest
            platform: linux

    runs-on: ${{ matrix.os }}
    env:
      UV_PYTHON: ${{ matrix.interpreter }}
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools
      - name: prepare profiling directory
        shell: bash
        run: mkdir -p ${{ github.workspace }}/profdata
      - name: Build initial wheel
        uses: PyO3/maturin-action@v1
        with:
          rust-toolchain: stable
          command: build
          args: --release --out pgo_wheel --interpreter ${{ matrix.interpreter }}
          manylinux: ${{ matrix.manylinux || 'auto' }}
          docker-options: -e CI
        env:
          RUSTFLAGS: "-Cprofile-generate=${{ github.workspace }}/profdata"
      - run: |
          RUST_HOST=$(rustc -Vv | grep host | cut -d ' ' -f 2) rustup run stable bash -c 'echo LLVM_PROFDATA=$RUSTUP_HOME/toolchains/$RUSTUP_TOOLCHAIN/lib/rustlib/$RUST_HOST/bin/llvm-profdata >> "$GITHUB_ENV"'
        shell: bash
      - name: Generate PGO data
        shell: bash
        run: |
          uv python install ${{ env.UV_PYTHON }}
          uv venv .venv
          uv sync --no-install-project --group test
          uv pip install rloop --no-index --no-deps --find-links pgo_wheel --force-reinstall
          LLVM_PROFILE_FILE=${{ github.workspace }}/profdata/rlp_%m_%p.profraw uv run --no-sync pytest tests
      - name: merge PGO data
        run: ${{ env.LLVM_PROFDATA }} merge --failure-mode=all -o ${{ github.workspace }}/merged.profdata ${{ github.workspace }}/profdata
      - name: Build PGO wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist --interpreter ${{ matrix.interpreter }}
          manylinux: ${{ matrix.manylinux || 'auto' }}
          rust-toolchain: stable
          docker-options: -e CI
        env:
          RUSTFLAGS: "-Cprofile-use=${{ github.workspace }}/merged.profdata"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-pgo-${{ matrix.platform || matrix.os }}-${{ matrix.interpreter }}
          path: dist
